version: '3.7'

services:
  api-mysql:
    image: mysql:5.7
    command: --sql_mode=""
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - api_db_data:/var/lib/mysql

  api-php:
    build: docker/php-fpm
    working_dir: /app
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - .:/app:cached
    depends_on:
      - api-mysql

  api-nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:cached
    depends_on:
      - api-php

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
  api_db_data:

###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
